spring.application.name=conduit-service

# SQLite datasource URL
spring.datasource.url=jdbc:sqlite:conduit.db?journal_mode=WAL&busy_timeout=30000
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate Dialect and DDL
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=create-drop

# Show SQL queries in the console
spring.jpa.show-sql=true

# JWT
jwt.secret-key=KlUjPRH90rTSz64c2yVc4aBJenaAbcWpi45/6tQyopM=
jwt.expiration-ms=604800000
